- authors.html
- chronology.html
- index.html
- riding/as-well.html
- riding/dimensions.html
- riding/gentlemen.html
- riding/index.html
- riding/poets-corner.html
- riding/prayer.html
- riding/quids.html
- roadmap.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/170
> six early poems by Laura Riding

- authors.html
- chronology.html
- index.html
- roadmap.html
- whittier/index.html
- whittier/snow-bound.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/184
> publish Whittier: Snow-Bound

- authors.html
- chronology.html
- index.html
- jeffers/beauty.html
- jeffers/boats.html
- jeffers/fog.html
- jeffers/index.html
- jeffers/joy.html
- jeffers/people.html
- jeffers/rock.html
- jeffers/stone-cutters.html
- roadmap.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/186
> publish Jeffers: early poems

- authors.html
- benet/american-names.html
- benet/index.html
- chronology.html
- index.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/12
> Benet: American Names

- chronology.html
- poems.html
- roadmap.html
- yeats/1919.html
- yeats/byzantium.html
- yeats/index.html
- yeats/schoolchildren.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/60
> Yeats: poems from The Tower

- chronology.html
- ibsen/index.html
- ibsen/lady-act1.html
- ibsen/lady-act2.html
- ibsen/lady-act3.html
- ibsen/lady-act4.html
- ibsen/lady-act5.html
- ibsen/lady-from-the-sea.html
- ibsen/lady-personae.html
- index.html
- plays.html
- roadmap.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/27
> Ibsen: The Lady from the Sea

- chronology.html
- eliot/brother-and-sister.html
- eliot/choir-invisible.html
- eliot/index.html
- eliot/self-and-life.html
- poems.html
- roadmap.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/117
> three George Eliot poems

- chronology.html
- gray/adversity.html
- gray/elegy.html
- gray/eton.html
- gray/index.html
- gray/spring.html
- gray/west.html
- poems.html
- roadmap.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/208
> five poems by Thomas Gray

- chronology.html
- index.html
- poems.html
- roadmap.html
- shelley/atheism.html
- shelley/cloud.html
- shelley/flight.html
- shelley/index.html
- shelley/invitation.html
- shelley/liberty.html
- shelley/masque.html
- shelley/ozymandias.html
- shelley/profaned.html
- shelley/recollection.html
- shelley/skylark.html
- shelley/slept.html
- shelley/weariness.html
- shelley/west-wind.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/206
> more poems by Shelley

- chronology.html
- index.html
- poems.html
- roadmap.html
- wordsworth/bleak.html
- wordsworth/buonaparte.html
- wordsworth/butterfly.html
- wordsworth/cloud.html
- wordsworth/cuckoo.html
- wordsworth/daisy.html
- wordsworth/early-spring.html
- wordsworth/heart.html
- wordsworth/index.html
- wordsworth/linnet.html
- wordsworth/london.html
- wordsworth/lycoris.html
- wordsworth/mostsweet.html
- wordsworth/peele.html
- wordsworth/phantom.html
- wordsworth/revolution.html
- wordsworth/september.html
- wordsworth/skylark.html
- wordsworth/sparrow.html
- wordsworth/stepping.html
- wordsworth/switzerland.html
- wordsworth/tintern-abbey.html
- wordsworth/toomuch.html
- wordsworth/toussaint.html
- wordsworth/venetian.html
- wordsworth/warrior.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/202
> more Wordsworth poems

- chronology.html
- collins/brave.html
- collins/evening.html
- collins/index.html
- collins/liberty.html
- collins/manners.html
- collins/passions.html
- collins/peace.html
- collins/simplicity.html
- collins/sonnet.html
- poems.html
- roadmap.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/209
> poems by William Collins

- authors.html
- chronology.html
- index.html
- poems.html
- roadmap.html
- waller/evelyn.html
- waller/index.html
- waller/isabella.html
- waller/jonson.html
- waller/last.html
- waller/listen.html
- waller/rose.html
- waller/sedley.html
- waller/self-banished.html
- waller/singing.html
- waller/story.html
- waller/thyrsis.html
- waller/verse.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/273
> poems by Edmund Waller

- authors.html
- bryant/fairest.html
- bryant/hudson.html
- bryant/index.html
- bryant/leggett.html
- bryant/lincoln.html
- bryant/not-yet.html
- bryant/planting.html
- bryant/snow-shower.html
- bryant/spell.html
- bryant/thanatopsis.html
- bryant/walk.html
- bryant/years.html
- chronology.html
- index.html
- poems.html
- roadmap.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/198
> poems by William Cullen Bryant

- chronology.html
- index.html
- millay/anguish.html
- millay/dirge-without-music.html
- millay/estranged.html
- millay/hardy-garden.html
- millay/index.html
- millay/lesbos.html
- millay/lethe.html
- millay/pao-chin.html
- millay/rhyme.html
- millay/song.html
- millay/wife.html
- millay/winter-night.html
- millay/without-pity.html
- millay/young-girl.html
- poems.html
- roadmap.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/51
> Millay: selections from The Buck in the Snow

- chronology.html
- hillyer/all-day.html
- hillyer/always-more.html
- hillyer/at-peace.html
- hillyer/august-afternoon.html
- hillyer/beneath.html
- hillyer/forever.html
- hillyer/great-desire.html
- hillyer/index.html
- hillyer/mariners.html
- hillyer/never-think.html
- hillyer/pan-of-the-crossroads.html
- hillyer/phantom-saint.html
- hillyer/ponder.html
- hillyer/springs-rebirth.html
- hillyer/stars.html
- hillyer/strong-wills.html
- hillyer/you-cannot-hear-me.html
- index.html
- poems.html
- roadmap.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/48
> poems from The Seventh Hill

- chronology.html
- index.html
- plays.html
- roadmap.html
- shakespeare/index.html
- shakespeare/julius_caesar.1.1.html
- shakespeare/julius_caesar.1.2.html
- shakespeare/julius_caesar.1.3.html
- shakespeare/julius_caesar.2.1.html
- shakespeare/julius_caesar.2.2.html
- shakespeare/julius_caesar.2.3.html
- shakespeare/julius_caesar.2.4.html
- shakespeare/julius_caesar.3.1.html
- shakespeare/julius_caesar.3.2.html
- shakespeare/julius_caesar.3.3.html
- shakespeare/julius_caesar.4.1.html
- shakespeare/julius_caesar.4.2.html
- shakespeare/julius_caesar.4.3.html
- shakespeare/julius_caesar.5.1.html
- shakespeare/julius_caesar.5.2.html
- shakespeare/julius_caesar.5.3.html
- shakespeare/julius_caesar.5.4.html
- shakespeare/julius_caesar.5.5.html
- shakespeare/juliuscaesar.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/257
> Shakespeare: Julius Caesar

- chronology.html
- index.html
- plays.html
- roadmap.html
- shakespeare/index.html
- shakespeare/merchant.1.1.html
- shakespeare/merchant.1.2.html
- shakespeare/merchant.1.3.html
- shakespeare/merchant.2.1.html
- shakespeare/merchant.2.2.html
- shakespeare/merchant.2.3.html
- shakespeare/merchant.2.4.html
- shakespeare/merchant.2.5.html
- shakespeare/merchant.2.6.html
- shakespeare/merchant.2.7.html
- shakespeare/merchant.2.8.html
- shakespeare/merchant.2.9.html
- shakespeare/merchant.3.1.html
- shakespeare/merchant.3.2.html
- shakespeare/merchant.3.3.html
- shakespeare/merchant.3.4.html
- shakespeare/merchant.3.5.html
- shakespeare/merchant.4.1.html
- shakespeare/merchant.4.2.html
- shakespeare/merchant.5.1.html
- shakespeare/merchantofvenice.html
fixes https://github.com/MonadnockValleyPress/monadnock/issues/234
> Shakespeare: The Merchant of Venice

- chronology.html
- index.html
- plays.html
- roadmap.html
- shakespeare/index.html
- shakespeare/twelfth_night.1.1.html
- shakespeare/twelfth_night.1.2.html
- shakespeare/twelfth_night.1.3.html
- shakespeare/twelfth_night.1.4.html
- shakespeare/twelfth_night.1.5.html
- shakespeare/twelfth_night.2.1.html
- shakespeare/twelfth_night.2.2.html
- shakespeare/twelfth_night.2.3.html
- shakespeare/twelfth_night.2.4.html
- shakespeare/twelfth_night.2.5.html
- shakespeare/twelfth_night.3.1.html
- shakespeare/twelfth_night.3.2.html
- shakespeare/twelfth_night.3.3.html
- shakespeare/twelfth_night.3.4.html
- shakespeare/twelfth_night.4.1.html
- shakespeare/twelfth_night.4.2.html
- shakespeare/twelfth_night.4.3.html
- shakespeare/twelfth_night.5.1.html
- shakespeare/twelfthnight.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/241
> Shakespeare: Twelfth Night

- chronology.html
- index.html
- plays.html
- roadmap.html
- shakespeare/index.html
- shakespeare/timon.1.1.html
- shakespeare/timon.1.2.html
- shakespeare/timon.2.1.html
- shakespeare/timon.2.2.html
- shakespeare/timon.3.1.html
- shakespeare/timon.3.2.html
- shakespeare/timon.3.3.html
- shakespeare/timon.3.4.html
- shakespeare/timon.3.5.html
- shakespeare/timon.3.6.html
- shakespeare/timon.4.1.html
- shakespeare/timon.4.2.html
- shakespeare/timon.4.3.html
- shakespeare/timon.5.1.html
- shakespeare/timon.5.2.html
- shakespeare/timon.5.3.html
- shakespeare/timon.5.4.html
- shakespeare/timonofathens.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/262
> Shakespeare: Timon of Athens

- chronology.html
- plays.html
- roadmap.html
- shakespeare/index.html
- shakespeare/tempest.1.1.html
- shakespeare/tempest.1.2.html
- shakespeare/tempest.2.1.html
- shakespeare/tempest.2.2.html
- shakespeare/tempest.3.1.html
- shakespeare/tempest.3.2.html
- shakespeare/tempest.3.3.html
- shakespeare/tempest.4.1.html
- shakespeare/tempest.5.1.html
- shakespeare/tempest.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/239
> Shakespeare: The Tempest

- chronology.html
- index.html
- plays.html
- roadmap.html
- shakespeare/index.html
- shakespeare/midsummer.1.1.html
- shakespeare/midsummer.1.2.html
- shakespeare/midsummer.2.1.html
- shakespeare/midsummer.2.2.html
- shakespeare/midsummer.3.1.html
- shakespeare/midsummer.3.2.html
- shakespeare/midsummer.4.1.html
- shakespeare/midsummer.4.2.html
- shakespeare/midsummer.5.1.html
- shakespeare/midsummer.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/235
> Shakespeare: A Midsummer Night's Dream

- chronology.html
- index.html
- plays.html
- roadmap.html
- shakespeare/asyoulikeit.1.1.html
- shakespeare/asyoulikeit.1.2.html
- shakespeare/asyoulikeit.1.3.html
- shakespeare/asyoulikeit.2.1.html
- shakespeare/asyoulikeit.2.2.html
- shakespeare/asyoulikeit.2.3.html
- shakespeare/asyoulikeit.2.4.html
- shakespeare/asyoulikeit.2.5.html
- shakespeare/asyoulikeit.2.6.html
- shakespeare/asyoulikeit.2.7.html
- shakespeare/asyoulikeit.3.1.html
- shakespeare/asyoulikeit.3.2.html
- shakespeare/asyoulikeit.3.3.html
- shakespeare/asyoulikeit.3.4.html
- shakespeare/asyoulikeit.3.5.html
- shakespeare/asyoulikeit.4.1.html
- shakespeare/asyoulikeit.4.2.html
- shakespeare/asyoulikeit.4.3.html
- shakespeare/asyoulikeit.5.1.html
- shakespeare/asyoulikeit.5.2.html
- shakespeare/asyoulikeit.5.3.html
- shakespeare/asyoulikeit.5.4.html
- shakespeare/asyoulikeit.html
- shakespeare/index.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/228
> Shakespeare: As You Like It

- chronology.html
- index.html
- plays.html
- roadmap.html
- shakespeare/index.html
- shakespeare/measure.1.1.html
- shakespeare/measure.1.2.html
- shakespeare/measure.1.3.html
- shakespeare/measure.1.4.html
- shakespeare/measure.2.1.html
- shakespeare/measure.2.2.html
- shakespeare/measure.2.3.html
- shakespeare/measure.2.4.html
- shakespeare/measure.3.1.html
- shakespeare/measure.3.2.html
- shakespeare/measure.4.1.html
- shakespeare/measure.4.2.html
- shakespeare/measure.4.3.html
- shakespeare/measure.4.4.html
- shakespeare/measure.4.5.html
- shakespeare/measure.4.6.html
- shakespeare/measure.5.1.html
- shakespeare/measureformeasure.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/232
> Shakespeare: Measure for Measure

- chronology.html
- index.html
- plays.html
- roadmap.html
- shakespeare/index.html
- shakespeare/kingjohn.1.1.html
- shakespeare/kingjohn.2.1.html
- shakespeare/kingjohn.3.1.html
- shakespeare/kingjohn.3.2.html
- shakespeare/kingjohn.3.3.html
- shakespeare/kingjohn.3.4.html
- shakespeare/kingjohn.4.1.html
- shakespeare/kingjohn.4.2.html
- shakespeare/kingjohn.4.3.html
- shakespeare/kingjohn.5.1.html
- shakespeare/kingjohn.5.2.html
- shakespeare/kingjohn.5.3.html
- shakespeare/kingjohn.5.4.html
- shakespeare/kingjohn.5.5.html
- shakespeare/kingjohn.5.6.html
- shakespeare/kingjohn.5.7.html
- shakespeare/kingjohn.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/251
> Shakespeare: King John

- chronology.html
- index.html
- plays.html
- roadmap.html
- shakespeare/index.html
- shakespeare/richardii.1.1.html
- shakespeare/richardii.1.2.html
- shakespeare/richardii.1.3.html
- shakespeare/richardii.1.4.html
- shakespeare/richardii.2.1.html
- shakespeare/richardii.2.2.html
- shakespeare/richardii.2.3.html
- shakespeare/richardii.2.4.html
- shakespeare/richardii.3.1.html
- shakespeare/richardii.3.2.html
- shakespeare/richardii.3.3.html
- shakespeare/richardii.3.4.html
- shakespeare/richardii.4.1.html
- shakespeare/richardii.5.1.html
- shakespeare/richardii.5.2.html
- shakespeare/richardii.5.3.html
- shakespeare/richardii.5.4.html
- shakespeare/richardii.5.5.html
- shakespeare/richardii.5.6.html
- shakespeare/richardii.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/252
> Shakespeare: Richard II

- chronology.html
- index.html
- plays.html
- roadmap.html
- shakespeare/1henryiv.1.1.html
- shakespeare/1henryiv.1.2.html
- shakespeare/1henryiv.1.3.html
- shakespeare/1henryiv.2.1.html
- shakespeare/1henryiv.2.2.html
- shakespeare/1henryiv.2.3.html
- shakespeare/1henryiv.2.4.html
- shakespeare/1henryiv.3.1.html
- shakespeare/1henryiv.3.2.html
- shakespeare/1henryiv.4.1.html
- shakespeare/1henryiv.4.2.html
- shakespeare/1henryiv.4.3.html
- shakespeare/1henryiv.4.4.html
- shakespeare/1henryiv.5.1.html
- shakespeare/1henryiv.5.2.html
- shakespeare/1henryiv.5.3.html
- shakespeare/1henryiv.5.4.html
- shakespeare/1henryiv.5.5.html
- shakespeare/1henryiv.html
- shakespeare/index.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/244
> Shakespeare: Henry IV, Part 1

- chronology.html
- index.html
- plays.html
- roadmap.html
- shakespeare/2henryiv.0.0.html
- shakespeare/2henryiv.1.1.html
- shakespeare/2henryiv.1.2.html
- shakespeare/2henryiv.1.3.html
- shakespeare/2henryiv.2.1.html
- shakespeare/2henryiv.2.2.html
- shakespeare/2henryiv.2.3.html
- shakespeare/2henryiv.2.4.html
- shakespeare/2henryiv.3.1.html
- shakespeare/2henryiv.3.2.html
- shakespeare/2henryiv.4.1.html
- shakespeare/2henryiv.4.2.html
- shakespeare/2henryiv.4.3.html
- shakespeare/2henryiv.4.4.html
- shakespeare/2henryiv.4.5.html
- shakespeare/2henryiv.5.1.html
- shakespeare/2henryiv.5.2.html
- shakespeare/2henryiv.5.3.html
- shakespeare/2henryiv.5.4.html
- shakespeare/2henryiv.5.5.html
- shakespeare/2henryiv.html
- shakespeare/index.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/245
> Shakespeare: Henry IV, Part 2

- chronology.html
- index.html
- plays.html
- roadmap.html
- shakespeare/index.html
- shakespeare/two_gentlemen.1.1.html
- shakespeare/two_gentlemen.1.2.html
- shakespeare/two_gentlemen.1.3.html
- shakespeare/two_gentlemen.2.1.html
- shakespeare/two_gentlemen.2.2.html
- shakespeare/two_gentlemen.2.3.html
- shakespeare/two_gentlemen.2.4.html
- shakespeare/two_gentlemen.2.5.html
- shakespeare/two_gentlemen.2.6.html
- shakespeare/two_gentlemen.2.7.html
- shakespeare/two_gentlemen.3.1.html
- shakespeare/two_gentlemen.3.2.html
- shakespeare/two_gentlemen.4.1.html
- shakespeare/two_gentlemen.4.2.html
- shakespeare/two_gentlemen.4.3.html
- shakespeare/two_gentlemen.4.4.html
- shakespeare/two_gentlemen.5.1.html
- shakespeare/two_gentlemen.5.2.html
- shakespeare/two_gentlemen.5.3.html
- shakespeare/two_gentlemen.5.4.html
- shakespeare/twogentlemenofverona.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/242
> Shakespeare: Two Gentlemen of Verona

- chronology.html
- index.html
- plays.html
- roadmap.html
- shakespeare/2henryvi.1.1.html
- shakespeare/2henryvi.1.2.html
- shakespeare/2henryvi.1.3.html
- shakespeare/2henryvi.1.4.html
- shakespeare/2henryvi.2.1.html
- shakespeare/2henryvi.2.2.html
- shakespeare/2henryvi.2.3.html
- shakespeare/2henryvi.2.4.html
- shakespeare/2henryvi.3.1.html
- shakespeare/2henryvi.3.2.html
- shakespeare/2henryvi.3.3.html
- shakespeare/2henryvi.4.1.html
- shakespeare/2henryvi.4.10.html
- shakespeare/2henryvi.4.2.html
- shakespeare/2henryvi.4.3.html
- shakespeare/2henryvi.4.4.html
- shakespeare/2henryvi.4.5.html
- shakespeare/2henryvi.4.6.html
- shakespeare/2henryvi.4.7.html
- shakespeare/2henryvi.4.8.html
- shakespeare/2henryvi.4.9.html
- shakespeare/2henryvi.5.1.html
- shakespeare/2henryvi.5.2.html
- shakespeare/2henryvi.5.3.html
- shakespeare/2henryvi.html
- shakespeare/index.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/248
> Shakespeare: Henry VI, Part 2

- chronology.html
- index.html
- plays.html
- roadmap.html
- shakespeare/allswell.1.1.html
- shakespeare/allswell.1.2.html
- shakespeare/allswell.1.3.html
- shakespeare/allswell.2.1.html
- shakespeare/allswell.2.2.html
- shakespeare/allswell.2.3.html
- shakespeare/allswell.2.4.html
- shakespeare/allswell.2.5.html
- shakespeare/allswell.3.1.html
- shakespeare/allswell.3.2.html
- shakespeare/allswell.3.3.html
- shakespeare/allswell.3.4.html
- shakespeare/allswell.3.5.html
- shakespeare/allswell.3.6.html
- shakespeare/allswell.3.7.html
- shakespeare/allswell.4.1.html
- shakespeare/allswell.4.2.html
- shakespeare/allswell.4.3.html
- shakespeare/allswell.4.4.html
- shakespeare/allswell.4.5.html
- shakespeare/allswell.5.1.html
- shakespeare/allswell.5.2.html
- shakespeare/allswell.5.3.html
- shakespeare/allswellthatendswell.html
- shakespeare/index.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/227
> Shakespeare: All's Well That Ends Well

- chronology.html
- index.html
- plays.html
- roadmap.html
- shakespeare/index.html
- shakespeare/titus.1.1.html
- shakespeare/titus.2.1.html
- shakespeare/titus.2.2.html
- shakespeare/titus.2.3.html
- shakespeare/titus.2.4.html
- shakespeare/titus.3.1.html
- shakespeare/titus.3.2.html
- shakespeare/titus.4.1.html
- shakespeare/titus.4.2.html
- shakespeare/titus.4.3.html
- shakespeare/titus.4.4.html
- shakespeare/titus.5.1.html
- shakespeare/titus.5.2.html
- shakespeare/titus.5.3.html
- shakespeare/titusandronicus.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/263
> Shakespeare: Titus Andronicus

- chronology.html
- index.html
- plays.html
- roadmap.html
- shakespeare/index.html
- shakespeare/winters_tale.1.1.html
- shakespeare/winters_tale.1.2.html
- shakespeare/winters_tale.2.1.html
- shakespeare/winters_tale.2.2.html
- shakespeare/winters_tale.2.3.html
- shakespeare/winters_tale.3.1.html
- shakespeare/winters_tale.3.2.html
- shakespeare/winters_tale.3.3.html
- shakespeare/winters_tale.4.1.html
- shakespeare/winters_tale.4.2.html
- shakespeare/winters_tale.4.3.html
- shakespeare/winters_tale.4.4.html
- shakespeare/winters_tale.5.1.html
- shakespeare/winters_tale.5.2.html
- shakespeare/winters_tale.5.3.html
- shakespeare/winterstale.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/243
> Shakespeare: Winter's Tale

- chronology.html
- plays.html
- roadmap.html
- shakespeare/index.html
- shakespeare/much_ado.1.1.html
- shakespeare/much_ado.1.2.html
- shakespeare/much_ado.1.3.html
- shakespeare/much_ado.2.1.html
- shakespeare/much_ado.2.2.html
- shakespeare/much_ado.2.3.html
- shakespeare/much_ado.3.1.html
- shakespeare/much_ado.3.2.html
- shakespeare/much_ado.3.3.html
- shakespeare/much_ado.3.4.html
- shakespeare/much_ado.3.5.html
- shakespeare/much_ado.4.1.html
- shakespeare/much_ado.4.2.html
- shakespeare/much_ado.5.1.html
- shakespeare/much_ado.5.2.html
- shakespeare/much_ado.5.3.html
- shakespeare/much_ado.5.4.html
- shakespeare/muchado.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/236
> Shakespeare: Much Ado About Nothing

- atom.xml
- chronology.html
- index.html
- plays.html
- roadmap.html
- shakespeare/comedy_errors.1.1.html
- shakespeare/comedy_errors.1.2.html
- shakespeare/comedy_errors.2.1.html
- shakespeare/comedy_errors.2.2.html
- shakespeare/comedy_errors.3.1.html
- shakespeare/comedy_errors.3.2.html
- shakespeare/comedy_errors.4.1.html
- shakespeare/comedy_errors.4.2.html
- shakespeare/comedy_errors.4.3.html
- shakespeare/comedy_errors.4.4.html
- shakespeare/comedy_errors.5.1.html
- shakespeare/comedyoferrors.html
- shakespeare/index.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/229
> Shakespeare: Comedy of Errors

- atom.xml
- chronology.html
- index.html
- plays.html
- roadmap.html
- shakespeare/index.html
- shakespeare/othello.1.1.html
- shakespeare/othello.1.2.html
- shakespeare/othello.1.3.html
- shakespeare/othello.2.1.html
- shakespeare/othello.2.2.html
- shakespeare/othello.2.3.html
- shakespeare/othello.3.1.html
- shakespeare/othello.3.2.html
- shakespeare/othello.3.3.html
- shakespeare/othello.3.4.html
- shakespeare/othello.4.1.html
- shakespeare/othello.4.2.html
- shakespeare/othello.4.3.html
- shakespeare/othello.5.1.html
- shakespeare/othello.5.2.html
- shakespeare/othello.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/260
> Shakespeare: Othello

- atom.xml
- chronology.html
- index.html
- plays.html
- roadmap.html
- shakespeare/index.html
- shakespeare/loves_labours_lost.1.1.html
- shakespeare/loves_labours_lost.1.2.html
- shakespeare/loves_labours_lost.2.1.html
- shakespeare/loves_labours_lost.3.1.html
- shakespeare/loves_labours_lost.4.1.html
- shakespeare/loves_labours_lost.4.2.html
- shakespeare/loves_labours_lost.4.3.html
- shakespeare/loves_labours_lost.5.1.html
- shakespeare/loves_labours_lost.5.2.html
- shakespeare/loveslabourslost.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/231
> Shakespeare: Love's Labours Lost

- atom.xml
- chronology.html
- index.html
- plays.html
- roadmap.html
- shakespeare/index.html
- shakespeare/taming_shrew.0.1.html
- shakespeare/taming_shrew.0.2.html
- shakespeare/taming_shrew.1.1.html
- shakespeare/taming_shrew.1.2.html
- shakespeare/taming_shrew.2.1.html
- shakespeare/taming_shrew.3.1.html
- shakespeare/taming_shrew.3.2.html
- shakespeare/taming_shrew.4.1.html
- shakespeare/taming_shrew.4.2.html
- shakespeare/taming_shrew.4.3.html
- shakespeare/taming_shrew.4.4.html
- shakespeare/taming_shrew.4.5.html
- shakespeare/taming_shrew.5.1.html
- shakespeare/taming_shrew.5.2.html
- shakespeare/tamingoftheshrew.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/238
> Shakespeare: Taming of the Shrew

- atom.xml
- authors.html
- carew/beautiful.html
- carew/cruel.html
- carew/disdain.html
- carew/divine.html
- carew/eternity.html
- carew/index.html
- carew/ingrateful.html
- carew/lady.html
- carew/mediocrity.html
- carew/murdering.html
- carew/persuasions.html
- carew/spring.html
- chronology.html
- index.html
- roadmap.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/389
> Thomas Carew: selected poems

- atom.xml
- authors.html
- chronology.html
- cowley/constantia.html
- cowley/counsel.html
- cowley/crashaw.html
- cowley/epicure.html
- cowley/epitaph.html
- cowley/fruition.html
- cowley/grasshopper.html
- cowley/inconstancy.html
- cowley/index.html
- cowley/life.html
- cowley/pindar.html
- cowley/platonic.html
- cowley/sleep.html
- cowley/sport.html
- cowley/supplication.html
- cowley/wish.html
- cowley/wotton.html
- index.html
- poems.html
- roadmap.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/390
> Cowley: selected poems

- atom.xml
- authors.html
- chronology.html
- index.html
- poems.html
- roadmap.html
- vaughan/absent.html
- vaughan/books.html
- vaughan/difference.html
- vaughan/friend.html
- vaughan/gone.html
- vaughan/index.html
- vaughan/parted.html
- vaughan/song.html
- vaughan/walking.html
- vaughan/weeping.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/327
> Vaughan: selected poems

- atom.xml
- authors.html
- blake/black-boy.html
- blake/blossom.html
- blake/boyfound.html
- blake/boylost1.html
- blake/cradle1.html
- blake/dream.html
- blake/green.html
- blake/image1.html
- blake/index.html
- blake/infant-joy.html
- blake/innocence.html
- blake/intro1.html
- blake/lamb.html
- blake/laughing.html
- blake/night.html
- blake/nurse1.html
- blake/shepherd.html
- blake/sorrow.html
- blake/spring.html
- blake/sweeper1.html
- blake/thursday1.html
- chronology.html
- index.html
- poems.html
- roadmap.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/386
> William Blake: Songs of Innocence

- atom.xml
- chronology.html
- epics.html
- index.html
- roadmap.html
- wordsworth/index.html
- wordsworth/prelude-1.html
- wordsworth/prelude-10.html
- wordsworth/prelude-11.html
- wordsworth/prelude-12.html
- wordsworth/prelude-13.html
- wordsworth/prelude-14.html
- wordsworth/prelude-2.html
- wordsworth/prelude-3.html
- wordsworth/prelude-4.html
- wordsworth/prelude-5.html
- wordsworth/prelude-6.html
- wordsworth/prelude-7.html
- wordsworth/prelude-8.html
- wordsworth/prelude-9.html
- wordsworth/prelude.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/384
> William Wordsworth: The Prelude

- atom.xml
- chronology.html
- ibsen/hedda-act1.html
- ibsen/hedda-act2.html
- ibsen/hedda-act3.html
- ibsen/hedda-act4.html
- ibsen/hedda-gabler.html
- ibsen/hedda-personae.html
- ibsen/index.html
- roadmap.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/50
> Ibsen: Hedda Gabler

- atom.xml
- chronology.html
- epics.html
- longfellow/evangeline-prelude.html
- longfellow/evangeline.1.1.html
- longfellow/evangeline.1.2.html
- longfellow/evangeline.1.3.html
- longfellow/evangeline.1.4.html
- longfellow/evangeline.1.5.html
- longfellow/evangeline.2.1.html
- longfellow/evangeline.2.2.html
- longfellow/evangeline.2.3.html
- longfellow/evangeline.2.4.html
- longfellow/evangeline.2.5.html
- longfellow/evangeline.html
- longfellow/index.html
- roadmap.html
Fixes https://github.com/MonadnockValleyPress/monadnock/issues/398
> Longfellow: Evangeline

- bronte-charlotte/index.html
There was a broken link to Jane Eyre! This minor tweak should fix it.
> fixed jane eyre link bug
